export const carsData = [
  {
    name: "Koenigsegg",
    type: "Sport",
    fuel: "90L",
    transmission: "Manual",
    passengers: "2 People",
    price: 99.0,
    image: "https://5.imimg.com/data5/VN/IV/GLADMIN-14988414/hyundai-sonata-car-250x250.jpg",
  },
  {
    name: "Nissan GT-R",
    type: "Sport",
    fuel: "80L",
    transmission: "Manual",
    passengers: "2 People",
    price: 80.0,
    image: "https://5.imimg.com/data5/VN/IV/GLADMIN-14988414/hyundai-sonata-car-250x250.jpg",
  },
  {
    name: "Rolls-Royce",
    type: "Sedan",
    fuel: "70L",
    transmission: "Manual",
    passengers: "4 People",
    price: 96.0,
    image: "https://5.imimg.com/data5/VN/IV/GLADMIN-14988414/hyundai-sonata-car-250x250.jpg",
  },
  {
    name: "All New Rush",
    type: "SUV",
    fuel: "70L",
    transmission: "Manual",
    passengers: "6 People",
    price: 72.0,
    image: "https://5.imimg.com/data5/VN/IV/GLADMIN-14988414/hyundai-sonata-car-250x250.jpg",
  },
  {
    name: "CR-V",
    type: "SUV",
    fuel: "80L",
    transmission: "Manual",
    passengers: "6 People",
    price: 80.0,
    image: "https://5.imimg.com/data5/VN/IV/GLADMIN-14988414/hyundai-sonata-car-250x250.jpg",
  },
  {
    name: "All New Terios",
    type: "SUV",
    fuel: "90L",
    transmission: "Manual",
    passengers: "6 People",
    price: 74.0,
    image: "https://5.imimg.com/data5/VN/IV/GLADMIN-14988414/hyundai-sonata-car-250x250.jpg",
  },
];
